### ISSUE TITLE
folia1.20加载报错 且功能无法生效

### ISSUE THREAD

**Issue by Jeffrey131313** [RenYuan-MC/CatSeedLogin#4]
[13:42:56 ERROR]: Could not pass event PlayerJoinEvent to CatSeedLogin v1.5.3-SNAPSHOT[Unofficial]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at cc.baka9.catseedlogin.bukkit.CatScheduler.teleport(CatScheduler.java:83) ~[CatSeedLogin (1).jar:?]
        at cc.baka9.catseedlogin.bukkit.Listeners.onPlayerJoin(Listeners.java:191) ~[CatSeedLogin (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:419) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleAcceptedLogin$1(ServerLoginPacketListenerImpl.java:204) ~[?:?]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue$ChunkBasedPriorityTask.executeInternal(RegionizedTaskQueue.java:504) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$PrioritisedQueue.executeTask(RegionizedTaskQueue.java:434) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.threadedregions.RegionizedTaskQueue$RegionTaskQueueData.drainTasks(RegionizedTaskQueue.java:263) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1514) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:360) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:385) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at cc.baka9.catseedlogin.bukkit.CatScheduler.teleport(CatScheduler.java:81) ~[CatSeedLogin (1).jar:?]
        ... 18 more
Caused by: java.lang.IllegalStateException: Player is already removed from player chunk loader
        at io.papermc.paper.chunk.system.RegionizedPlayerChunkLoader.removePlayer(RegionizedPlayerChunkLoader.java:158) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.level.ChunkMap.removePlayerFromDistanceMaps(ChunkMap.java:210) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.level.ChunkMap.updatePlayerStatus(ChunkMap.java:1017) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.level.ChunkMap.removeEntity(ChunkMap.java:1104) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.server.level.ServerChunkCache.removeEntity(ServerChunkCache.java:730) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.onTrackingEnd(ServerLevel.java:2859) ~[?:?]
        at net.minecraft.server.level.ServerLevel$EntityCallbacks.b(ServerLevel.java:2737) ~[?:?]
        at io.papermc.paper.chunk.system.entity.EntityLookup.entityStatusChange(EntityLookup.java:291) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at io.papermc.paper.chunk.system.entity.EntityLookup$EntityCallback.a(EntityLookup.java:884) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.world.entity.Entity.setRemoved(Entity.java:5493) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.world.entity.Entity.remove(Entity.java:706) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at net.minecraft.world.entity.LivingEntity.remove(LivingEntity.java:763) ~[?:?]
        at net.minecraft.world.entity.player.Player.remove(Player.java:1497) ~[?:?]
        at net.minecraft.server.level.ServerLevel.removePlayerImmediately(ServerLevel.java:1765) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.transformForAsyncTeleport(ServerPlayer.java:1398) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.transformForAsyncTeleport(ServerPlayer.java:190) ~[?:?]
        at net.minecraft.world.entity.Entity.teleportAsync(Entity.java:3924) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.lambda$teleportAsync$2(CraftEntity.java:1329) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftEntity.teleportAsync(CraftEntity.java:1344) ~[kaiiju-1.20.1.jar:git-Kaiiju-"8c562b0"]
        at org.bukkit.entity.Entity.teleportAsync(Entity.java:200) ~[kaiiju-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
        at cc.baka9.catseedlogin.bukkit.CatScheduler.teleport(CatScheduler.java:81) ~[CatSeedLogin (1).jar:?]

**Comment by GeJi2333** [comment]
同上 希望得到解决

**Comment by lRENyaaa** [comment]
抱歉之前一直没看到此issue,此问题将在几天内修复

**Comment by lRENyaaa** [comment]
应已在 https://github.com/RenYuan-MC/CatSeedLogin/commit/50be92623402a7cbba22c71791f4c61e6153c842 修复,Folia下测试无问题
